export const ACCOUNT_SIZES = [5000, 10000, 25000, 50000, 100000, 200000] as const

export const ACCOUNT_PRICES: Record<number, { evaluation: number; instant: number }> = {
  5000: { evaluation: 49, instant: 99 },
  10000: { evaluation: 79, instant: 159 },
  25000: { evaluation: 149, instant: 299 },
  50000: { evaluation: 249, instant: 499 },
  100000: { evaluation: 399, instant: 799 },
  200000: { evaluation: 699, instant: 1399 },
}

export const DEFAULT_RULES: Record<string, Record<string, any>> = {
  evaluation_1: {
    profitTarget: 8,
    maxDailyLoss: 6,
    maxOverallLoss: 10,
    maxPositionSize: 5,
    maxLeverage: 100,
    maxOpenTrades: 10,
    minTradingDays: 5,
    maxTradingDays: 30,
  },
  evaluation_2: {
    profitTarget: 5,
    maxDailyLoss: 6,
    maxOverallLoss: 10,
    maxPositionSize: 5,
    maxLeverage: 100,
    maxOpenTrades: 10,
    minTradingDays: 5,
    maxTradingDays: 60,
  },
  funded: {
    profitTarget: null,
    maxDailyLoss: 6,
    maxOverallLoss: 10,
    maxPositionSize: 5,
    maxLeverage: 100,
    maxOpenTrades: 10,
    minTradingDays: null,
    maxTradingDays: null,
  },
}

export const DEFAULT_RULES_BY_SIZE: Record<number, Record<string, Record<string, any>>> = {
  5000: {
    evaluation_1: {
      profitTarget: 8,
      maxDailyLoss: 4,
      maxOverallLoss: 8,
      maxPositionSize: 2,
      maxLeverage: 100,
      maxOpenTrades: 5,
      minTradingDays: 5,
      maxTradingDays: 30,
    },
    evaluation_2: {
      profitTarget: 5,
      maxDailyLoss: 4,
      maxOverallLoss: 8,
      maxPositionSize: 2,
      maxLeverage: 100,
      maxOpenTrades: 5,
      minTradingDays: 5,
      maxTradingDays: 60,
    },
    funded: {
      profitTarget: null,
      maxDailyLoss: 4,
      maxOverallLoss: 8,
      maxPositionSize: 3,
      maxLeverage: 100,
      maxOpenTrades: 5,
      minTradingDays: null,
      maxTradingDays: null,
    },
  },
  10000: {
    evaluation_1: {
      profitTarget: 8,
      maxDailyLoss: 4,
      maxOverallLoss: 8,
      maxPositionSize: 2.5,
      maxLeverage: 100,
      maxOpenTrades: 8,
      minTradingDays: 5,
      maxTradingDays: 30,
    },
    evaluation_2: {
      profitTarget: 5,
      maxDailyLoss: 4,
      maxOverallLoss: 8,
      maxPositionSize: 2.5,
      maxLeverage: 100,
      maxOpenTrades: 8,
      minTradingDays: 5,
      maxTradingDays: 60,
    },
    funded: {
      profitTarget: null,
      maxDailyLoss: 4,
      maxOverallLoss: 8,
      maxPositionSize: 5,
      maxLeverage: 100,
      maxOpenTrades: 8,
      minTradingDays: null,
      maxTradingDays: null,
    },
  },
  25000: {
    evaluation_1: {
      profitTarget: 8,
      maxDailyLoss: 5,
      maxOverallLoss: 10,
      maxPositionSize: 5,
      maxLeverage: 100,
      maxOpenTrades: 10,
      minTradingDays: 5,
      maxTradingDays: 30,
    },
    evaluation_2: {
      profitTarget: 5,
      maxDailyLoss: 5,
      maxOverallLoss: 10,
      maxPositionSize: 5,
      maxLeverage: 100,
      maxOpenTrades: 10,
      minTradingDays: 5,
      maxTradingDays: 60,
    },
    funded: {
      profitTarget: null,
      maxDailyLoss: 5,
      maxOverallLoss: 10,
      maxPositionSize: 7.5,
      maxLeverage: 100,
      maxOpenTrades: 10,
      minTradingDays: null,
      maxTradingDays: null,
    },
  },
  50000: {
    evaluation_1: {
      profitTarget: 8,
      maxDailyLoss: 5,
      maxOverallLoss: 10,
      maxPositionSize: 5,
      maxLeverage: 100,
      maxOpenTrades: 10,
      minTradingDays: 5,
      maxTradingDays: 30,
    },
    evaluation_2: {
      profitTarget: 5,
      maxDailyLoss: 5,
      maxOverallLoss: 10,
      maxPositionSize: 5,
      maxLeverage: 100,
      maxOpenTrades: 10,
      minTradingDays: 5,
      maxTradingDays: 60,
    },
    funded: {
      profitTarget: null,
      maxDailyLoss: 5,
      maxOverallLoss: 10,
      maxPositionSize: 10,
      maxLeverage: 100,
      maxOpenTrades: 10,
      minTradingDays: null,
      maxTradingDays: null,
    },
  },
  100000: {
    evaluation_1: {
      profitTarget: 8,
      maxDailyLoss: 5,
      maxOverallLoss: 10,
      maxPositionSize: 5,
      maxLeverage: 100,
      maxOpenTrades: 15,
      minTradingDays: 5,
      maxTradingDays: 30,
    },
    evaluation_2: {
      profitTarget: 5,
      maxDailyLoss: 5,
      maxOverallLoss: 10,
      maxPositionSize: 5,
      maxLeverage: 100,
      maxOpenTrades: 15,
      minTradingDays: 5,
      maxTradingDays: 60,
    },
    funded: {
      profitTarget: null,
      maxDailyLoss: 5,
      maxOverallLoss: 10,
      maxPositionSize: 10,
      maxLeverage: 100,
      maxOpenTrades: 15,
      minTradingDays: null,
      maxTradingDays: null,
    },
  },
  200000: {
    evaluation_1: {
      profitTarget: 8,
      maxDailyLoss: 5,
      maxOverallLoss: 10,
      maxPositionSize: 5,
      maxLeverage: 100,
      maxOpenTrades: 20,
      minTradingDays: 5,
      maxTradingDays: 30,
    },
    evaluation_2: {
      profitTarget: 5,
      maxDailyLoss: 5,
      maxOverallLoss: 10,
      maxPositionSize: 5,
      maxLeverage: 100,
      maxOpenTrades: 20,
      minTradingDays: 5,
      maxTradingDays: 60,
    },
    funded: {
      profitTarget: null,
      maxDailyLoss: 5,
      maxOverallLoss: 10,
      maxPositionSize: 10,
      maxLeverage: 100,
      maxOpenTrades: 20,
      minTradingDays: null,
      maxTradingDays: null,
    },
  },
}

export const PROFIT_SPLIT = 0.8

export interface SymbolInfo {
  digits: number
  pipValue: number
  contractSize: number
  margin: number
  category: 'crypto' | 'forex' | 'metals' | 'indices' | 'stocks' | 'rwa'
}

export const SYMBOLS: Record<string, SymbolInfo> = {
  BTCUSDT: { digits: 2, pipValue: 0.01, contractSize: 1, margin: 5000, category: 'crypto' },
  ETHUSDT: { digits: 2, pipValue: 0.01, contractSize: 1, margin: 2000, category: 'crypto' },
  SOLUSDT: { digits: 2, pipValue: 0.01, contractSize: 1, margin: 2000, category: 'crypto' },
  XRPUSDT: { digits: 4, pipValue: 0.0001, contractSize: 1, margin: 1000, category: 'crypto' },
  BNBUSDT: { digits: 2, pipValue: 0.01, contractSize: 1, margin: 2000, category: 'crypto' },
  ADAUSDT: { digits: 4, pipValue: 0.0001, contractSize: 1, margin: 500, category: 'crypto' },
  DOGEUSDT: { digits: 5, pipValue: 0.00001, contractSize: 1, margin: 500, category: 'crypto' },
  AVAXUSDT: { digits: 2, pipValue: 0.01, contractSize: 1, margin: 1000, category: 'crypto' },
  DOTUSDT: { digits: 3, pipValue: 0.001, contractSize: 1, margin: 500, category: 'crypto' },
  LINKUSDT: { digits: 3, pipValue: 0.001, contractSize: 1, margin: 500, category: 'crypto' },
  POLUSDT: { digits: 4, pipValue: 0.0001, contractSize: 1, margin: 500, category: 'crypto' },
  UNIUSDT: { digits: 3, pipValue: 0.001, contractSize: 1, margin: 500, category: 'crypto' },
  LTCUSDT: { digits: 2, pipValue: 0.01, contractSize: 1, margin: 500, category: 'crypto' },
  ARBUSDT: { digits: 3, pipValue: 0.001, contractSize: 1, margin: 500, category: 'crypto' },
  OPUSDT: { digits: 3, pipValue: 0.001, contractSize: 1, margin: 500, category: 'crypto' },
  APTUSDT: { digits: 3, pipValue: 0.001, contractSize: 1, margin: 500, category: 'crypto' },
  SUIUSDT: { digits: 3, pipValue: 0.001, contractSize: 1, margin: 500, category: 'crypto' },
  MKRUSDT: { digits: 1, pipValue: 0.1, contractSize: 1, margin: 5000, category: 'rwa' },
  ONDOUSDT: { digits: 4, pipValue: 0.0001, contractSize: 1, margin: 500, category: 'rwa' },
  PENDLEUSDT: { digits: 4, pipValue: 0.0001, contractSize: 1, margin: 500, category: 'rwa' },
  CFGUSDT: { digits: 5, pipValue: 0.00001, contractSize: 1, margin: 500, category: 'rwa' },
  POLYXUSDT: { digits: 5, pipValue: 0.00001, contractSize: 1, margin: 200, category: 'rwa' },
  OMUSDT: { digits: 5, pipValue: 0.00001, contractSize: 1, margin: 200, category: 'rwa' },
  DUSKUSDT: { digits: 5, pipValue: 0.00001, contractSize: 1, margin: 200, category: 'rwa' },
  TRUUSDT: { digits: 6, pipValue: 0.000001, contractSize: 1, margin: 200, category: 'rwa' },
}

export const COMMISSION: Record<string, number> = {
  crypto: 0,
  forex: 0,
  metals: 0,
  indices: 0,
  stocks: 0,
  rwa: 0,
}

export const SPREAD_MARKUP: Record<string, number> = {
  crypto: 0,
  forex: 0.2,
  metals: 0.1,
  indices: 0.5,
  stocks: 1,
  rwa: 0,
}

export const SWAP_RATES: Record<string, { long: number; short: number }> = {
  crypto: { long: -20.0, short: -20.0 },
  forex: { long: -5.0, short: -3.0 },
  metals: { long: -8.0, short: -6.0 },
  indices: { long: -3.0, short: -1.0 },
  stocks: { long: -2.0, short: -1.0 },
  rwa: { long: -20.0, short: -20.0 },
}
